<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('users')->insert([
            [
                'name' => 'admin',
                'email' => 'admin@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'superadmin',
                'placement' => null,
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana aceh
            [
                'name' => 'creator upt banda aceh',
                'email' => 'creatoraceh@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt banda aceh',
                'email' => 'checkeraceh@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt banda aceh',
                'email' => 'approveraceh@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // kantor induk
            [
                'name' => 'creator kantor induk',
                'email' => 'creatorinduk@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'main_office',
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker kantor induk',
                'email' => 'checkerinduk@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'main_office',
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver kantor induk',
                'email' => 'approverinduk@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'main_office',
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver 2 kantor induk',
                'email' => 'approver2induk@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver_2',
                'placement' => 'main_office',
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver 3 kantor induk',
                'email' => 'approver3induk@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver_3',
                'placement' => 'main_office',
                'unit_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana pematang siantar
            [
                'name' => 'creator upt medan',
                'email' => 'creatormedan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt medan',
                'email' => 'checkermedan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt medan',
                'email' => 'approvermedan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana pematang siantar
            [
                'name' => 'creator upt pematang siantar',
                'email' => 'creatorsiantar@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt pematang siantar',
                'email' => 'checkersiantar@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt pematang siantar',
                'email' => 'approversiantar@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana jambi
            [
                'name' => 'creator upt jambi',
                'email' => 'creatorjambi@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt jambi',
                'email' => 'checkerjambi@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt jambi',
                'email' => 'approverjambi@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana bengkulu
            [
                'name' => 'creator upt bengkulu',
                'email' => 'creatorbengkulu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt bengkulu',
                'email' => 'checkerbengkulu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt bengkulu',
                'email' => 'approverbengkulu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // unit pelaksana pekanbaru
            [
                'name' => 'creator upt pekanbaru',
                'email' => 'creatorpekanbaru@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt pekanbaru',
                'email' => 'checkerpekanbaru@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt pekanbaru',
                'email' => 'approverpekanbaru@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana padang
            [
                'name' => 'creator upt padang',
                'email' => 'creatorpadang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt padang',
                'email' => 'checkerpadang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt padang',
                'email' => 'approverpadang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana baturaja
            [
                'name' => 'creator upt baturaja',
                'email' => 'creatorbaturaja@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt baturaja',
                'email' => 'checkerbaturaja@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt baturaja',
                'email' => 'approverbaturaja@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana palembang
            [
                'name' => 'creator upt palembang',
                'email' => 'creatorpalembang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt palembang',
                'email' => 'checkerpalembang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt palembang',
                'email' => 'approverpalembang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana tanjung karang
            [
                'name' => 'creator upt tanjung karang',
                'email' => 'creatortanjungkarang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt tanjung karang',
                'email' => 'checkertanjungkarang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt tanjung karang',
                'email' => 'approvertanjungkarang@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana padang sidempuan
            [
                'name' => 'creator upt padang sidempuan',
                'email' => 'creatorpadangsidempuan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker upt padang sidempuan',
                'email' => 'checkerpadangsidempuan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver upt padang sidempuan',
                'email' => 'approverpadangsidempuan@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana up2b sbu
            [
                'name' => 'creator up2b sbu',
                'email' => 'creatorup2bsbu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker up2b sbu',
                'email' => 'checkerup2bsbu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver up2b sbu',
                'email' => 'approverup2bsbu@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana up2b sbt
            [
                'name' => 'creator up2b sbt',
                'email' => 'creatorup2bsbt@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker up2b sbt',
                'email' => 'checkerup2bsbt@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver up2b sbt',
                'email' => 'approverup2bsbt@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // unit pelaksana up2b sbs
            [
                'name' => 'creator up2b sbs',
                'email' => 'creatorup2bsbs@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'creator',
                'placement' => 'executor_unit',
                'unit_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'checker up2b sbs',
                'email' => 'checkerup2bsbs@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'checker',
                'placement' => 'executor_unit',
                'unit_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'approver up2b sbs',
                'email' => 'approverup2bsbs@pln.com',
                'password' => bcrypt('12345'),
                'type' => 'approver',
                'placement' => 'executor_unit',
                'unit_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
